### ISSUE TITLE
Add crypto as crypto-js

### ISSUE THREAD

**Issue by arun3528** [cyco130/esbuild-plugin-polyfill-node#1]
can you also add crypto to crypto-js ?
https://www.npmjs.com/package/crypto-js

**Comment by cyco130** [comment]
Hi,

`crypto-js` is not a `crypto` polyfill, they have different APIs (although I think one could be built upon it). [`crypto-browserify`](https://github.com/crypto-browserify/crypto-browserify) is but it's very quite big and misses a lot of features.

I just published version `0.0.2` and it supports polyfilling `crypto` and `fs` but only if you explicitly enable them in the options. These polyfills are huge and they don't make much sense on edge environments that this plugin is geared towards. If you need `crypto` in your app, consider using the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) instead. If a dependency requires it, try replacing it with something that uses the web version. Seriously, it adds about 390K which is more than one third of Cloudflare Workers' size limit for example.

Also, this plugin is very much untested (I haven't even publicly announced it yet :) ). You may want to use the equivalents from the [`esbuild-plugins`](https://github.com/remorses/esbuild-plugins) package (namely `@esbuild-plugins/node-modules-polyfill` and `@esbuild-plugins/node-globals-polyfill`). They haven't been updated for some time but they're probably much more stable than this one. Another option is [`esbuild-plugin-brode`](https://github.com/geut/brode/tree/main/packages/esbuild-plugin-brode) which I haven't tried but seems quite active.
