### ISSUE TITLE
Modern node polyfills

### ISSUE THREAD

**Issue by Aslemammad** [cyco130/esbuild-plugin-polyfill-node#2]
I wanted to mention that I worked on something called [modern-node-polyfills](https://github.com/Aslemammad/modern-node-polyfills) that is based on the modern jspm node polyfills (which work really well in production). 
You can consider using it under the hood of this tool.

**Comment by cyco130** [comment]
Awesome, thanks!

I know some of the browserify polyfills are a bit old, good to know jspm has replacements. They also add a few missing pieces like `fs/promises`. After I add proper tests, I can add a `jspm` option to use their versions and maybe even make it default.

**Comment by Aslemammad** [comment]
Yep, feel free to do so! Thanks.

**Comment by cyco130** [comment]
Hi, I did switch to JSPM polyfills but I decided to resolve them myself directly instead of using an intermediate library.

Thank you for showing me they existed!

**Comment by Aslemammad** [comment]
I appreciate it!
