### ISSUE TITLE
Import for "os" is broken in browser

### ISSUE THREAD

**Issue by patdx** [cyco130/esbuild-plugin-polyfill-node#3]
The "os" polyfill loads this file: https://unpkg.com/browse/os@0.1.2/index.js

Which, in browser environment, just creates an infinite loop.

I think something like os-browserify/browser.js would be more useful:

https://unpkg.com/browse/os-browserify@0.3.0/browser.js

**Comment by cyco130** [comment]
You're absolutely right. Fixed in 0.1.3, thanks for reporting.

I'll add tests and an option to use the more modern [jspm polyfills](https://github.com/cyco130/esbuild-plugin-polyfill-node/issues/2) before 1.0.
