### ISSUE TITLE
stream polyfill

### ISSUE THREAD

**Issue by tbruun** [cyco130/esbuild-plugin-polyfill-node#6]
Hi.
Would you consider replacing the "stream" dependency with "stream-browserify" [like so](https://github.com/tbruun/esbuild-plugin-polyfill-node/pull/1/files
)?

The "stream" dependency is very old and uses a very old stream API.

**Comment by cyco130** [comment]
I was planning on switching to JSPM polyfills, at least as an option (see #2) but didn't have the time yet.

Would you like to send a PR? Otherwise I can do it in a few days.

**Comment by tbruun** [comment]
If you're planning on switching I can wait as I have already published a [temporary forked package](https://www.npmjs.com/package/@tbruun/esbuild-plugin-polyfill-node).

With the current version of your dependency any calls to stream.Transform fails (at least for me)

**Comment by cyco130** [comment]
OK, let's keep this open. I'll do the switch at the first opportunity or just update `stream` package is it takes long.

**Comment by cyco130** [comment]
Hi,

I finally made the switch and released it as version `0.2.0`. Hope it solves your problems.
